site_name: CSC Rulebook
site_url: https://techlover1.github.io/rulebook/
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
    - 1 - Introduction: 1_introduction.md
    - 2 - League Info: 2_league-info.md
    - 3 - CSC Conduct Guidelines: 3_csc-conduct-guidelines.md
    - 4 - League Processes: 4_league-processes.md
    - 5 - Transactions: 5_transactions.md
    - 6 - Gameplay Rules: 6_gameplay-rules.md
    - 7-10 - Season Overview: 7_season-overview.md
    - Rules Committee Policies: X_rc-policies.md
    - Appendix: Y_appendix.md
